### ISSUE TITLE
"Aktuelles Datum voreingestellt" bei datetime_local Feld funktioniert nicht.

### ISSUE THREAD

**Issue by godsdog** [alexplusde/yform_field#15]
Wenn ich "Aktuelles Datum voreingestellt" bei dem datetime_local Feld **nicht** aktiviere, wird dennoch das aktuelle Datum beim Anelgen eines Datensatzes angezeigt.

**Comment by godsdog** [comment]
Habs mal in der datetime_local.php für mich lokal gefixt:
```

 public function enterObject()
    {
        $value = (string) $this->getValue();

        $this->setValue(str_replace("T", " ", (string) $this->getValue()));

        $this->params['value_pool']['email'][$this->getName()] = $this->getValue();
        if ($this->saveInDb()) {
            $this->params['value_pool']['sql'][$this->getName()] = $this->getValue();
        }

        if (!$this->needsOutput() && !$this->isViewable()) {
            return;
        }

        if (!$this->isEditable()) {
            $this->params['form_output'][$this->getId()] = $this->parse(
                ['value.datetime-view.tpl.php', 'value.date-view.tpl.php', 'value.view.tpl.php'],
                ['type' => 'text', 'value' => $this->getValue()]
            );
        } else {
               // FIX
            $dateValue = ('' != $this->getValue()) ? date_create($this->getValue()) : $this->getValue();
               // FIX
            $this->params['form_output'][$this->getId()] = $this->parse(
                ['value.text.tpl.php'],
                ['type' => 'datetime-local', 'min' => $this->getElement('min'), 'max' => $this->getElement('max'), 'value' => date_format($dateValue, 'Y-m-d\TH:i')]
            );
        }
    }
```

Folgende Zeile: 
`$dateValue = ('' != $this->getValue()) ? date_create($this->getValue()) : $this->getValue();`

Schau gerne mal ob das so passt, könnte dann einen PR machen...

**Comment by alxndr-w** [comment]
Wenns funktioniert, dann gerne direkt als PR. Da sehe ich dann auch, was geändert wird - aus der Issue-Beschreibung werde ich ehrlich gesagt gerade nicht ganz schlau.

Ich erinnere mich auch, dass ich das nicht explizit überprüft habe, insofern glaube ich, dass du das damit richtig gelöst hast.

**Comment by alxndr-w** [comment]
Ah, es wurde gar nicht das Datum gespeichert, sondern einfach nur unsauber ausgegeben. Denn das Veröffentlichungsdatum darf bis zur Veröffentlichung sehr wohl leer bleiben.

Mnn muss das in der Ausgabe der List Value fixen.

Für mein Addon `neues`, wird das Veröffentlichungsdatum an den Status gekoppelt, deswegen muss das Feld auch leer lassen dürfen.

1. kein publishdate + status 0: Entwurf
2. publishdate + status = 0: Geplante Veröffentlichung
3. publishdate + status = 1: Veröffentlicht
4. kein publishdate + status = 1: ungültig

Ich mache hier deswegen erstmal zu.

**Comment by alxndr-w** [comment]
Und für den Fall, dass ich etwas missverstanden habe - in der aktuellen Version wird das Datum nicht voreingestellt (Google Chrome)

![image](https://user-images.githubusercontent.com/3855487/209680607-7a128260-c68f-4b73-b270-66b213e4d8b1.png)
