### ISSUE TITLE
Action attach: uploadfields check falsch

### ISSUE THREAD

**Issue by godsdog** [alexplusde/yform_field#17]
In der `attach.php` müsste es glaube ich so sein, oder?:

```
if (count($fields)) {
            if ($override) {
                $email_attachments = [];
            }
            foreach ($fields as $field) {
                $email_attachments[] = $uploaded_files[$field];
            }	

        } else {
            if ($override) {
                $email_attachments = [];
            }
            foreach ($uploaded_files as $file) {
                $email_attachments[] = $file;
            }
        }
```
statt:
```
if (count($fields)) {
            if ($override) {
                $email_attachments = [];
            }
            foreach ($uploaded_files as $file) {
                $email_attachments[] = $file;
            }
        } else {
            if ($override) {
                $email_attachments = [];
            }
            foreach ($fields as $field) {
                $email_attachments[] = $uploaded_files[$field];
            }	
        }
```

**Comment by alxndr-w** [comment]
Danke für den Hinweis! Du kannst direkt die Datei hier auf Github bearbeiten und einen PR einreichen, dann schau ich es mir genauer an.

Was passiert denn / passiert nicht?

**Comment by godsdog** [comment]
Ich habe mir erst mal nur deinen Code angeschaut um zu verstehen, wie die Action genau funktioniert :)
DAbei ist mir das aufgefallen, hatte diese noch garnicht getestet...

**Comment by alxndr-w** [comment]
Ich bin mir nicht sicher, ob du die neuste Version im Einsatz hattest, denn hier auf GitHub und damit eig. auch in Version 2.0 sieht der Code ja auch ganz anders aus.

https://github.com/alexplusde/yform_field/blob/main/lib/yform/action/attach/attach.php
