### ISSUE TITLE
V2.2.0 Update knallt

### ISSUE THREAD

**Issue by godsdog** [alexplusde/yform_field#35]
Addon Version: 2.2.0
REDAXO 5.14.2
PHP 7.4.33

Update von 2.2.0 auf 2.2.1:
`Package "yform_field": the page path "install.php" neither exists as standalone path nor as package subpath "/www/htdocs/redaxo/src/addons/yform_field/install.php"`

Update von 2.2.0 auf 2.2.2:
`Call to undefined method rex_scss_compiler::setOutputStyle()`

**Comment by christophboecker** [comment]
@godsdog Moin, ist im Repo schon behoben (#34). Release 2.2.3 fehlt noch.
@alxndr-w Kann ich das Release auch bauen?  Wobei, wäre mir aus Konsistenz-Gründen lieber, wenn Du es machst.

**Comment by godsdog** [comment]
Alles klar, Danke für die Rückmeldung!

**Comment by alxndr-w** [comment]
@christophboecker gerne diesmal direkt releasen (Versionsnummer noch anpassen), ich entferne heute Abend noch die defekten Releases aus dem Installer.

**Comment by alxndr-w** [comment]
Ich habe es jetzt gemacht und hoffe, es passt so.

Danke @godsdog dennoch fürs Melden.
