### ISSUE TITLE
Feld "tabs" lässt sich nicht speichern 

### ISSUE THREAD

**Issue by MC-PMOE** [alexplusde/yform_field#53]
**Fehlermeldung:**
`Error while executing statement "SELECT `id`,`prio`,`label`,`name`,`group_by` FROM rex_yform_field WHERE `table_name`=:tablename AND `type_name`=:typename AND `id`!=:id AND `group_by`!=:group ORDER BY `group_by`,`prio` ASC" using params {":tablename":"rex_lp_places",":typename":"tabs",":id":-1,":group":"general"}! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'group_by' in 'field list'`

**Hintergrund:**
Scheinbar ist das Feld "group_by" nicht standardmäßig in der Tabelle "rex_yform_field" enthalten. Da das mit dem Tabs bei uns intern in einer anderen Redaxo-Instanz funktionierte, kamen wir zu der Kenntnis, dass die Spalte "group_by" erst durch das Installieren von "ycom" erstellt wird.

**Comment by christophboecker** [comment]
Fehlende Spalten in rex_yform_field werden automatisch angelegt, wenn ein Value hinzugefügt wird. Das passiert beim Speichern, weshalb die Tabelle rex_yform_field im Laufe der Zeit immer breiter wird. Wann und wie im Ablauf tritt den der Fehler auf?

**Comment by christophboecker** [comment]
Also Table-Manager, Feld angelegt, "Speichern" und rumms. Dann hab ich nen Verdacht, woran es liegen könnte.

**Comment by MC-PMOE** [comment]
Ergänzung:
Redaxo: 5.15.1
DB: MariaDB 10.5.21
PHP: 8.1.21
YForm: 4.1.1
yform_field: 2.3.1

**Comment by MC-PMOE** [comment]
> Also Table-Manager, Feld angelegt, "Speichern" und rumms. Dann hab ich nen Verdacht, woran es liegen könnte.

Genau, komme gar nicht erst dazu es zu verwenden

**Comment by alxndr-w** [comment]
@MC-PMOE kannst du probieren, den table manager zu reinstallieren und danach yform_field?

**Comment by christophboecker** [comment]
Das Problem hab ich identifizert; liegt nicht an TableManager oder YFF. Es gibt im Feld-Formular einen Validator, der unerlaubt verschachtelte Gruppen bei der Erfassung verhindern soll. 

https://github.com/alexplusde/yform_field/blob/dc3a55d66a26d6e226553f16059305ee1b7b7727/lib/yform/value/tabs.php#L179-L181

Wenn es aber noch kein eingetragenes Tabs-Feld gibt und nicht aus anderer Quelle zufällig "group_by" schon existiert, geht die zugehörige SQL-Abfrage logischer Weise auf die Bretter. 

https://github.com/alexplusde/yform_field/blob/dc3a55d66a26d6e226553f16059305ee1b7b7727/lib/yform/value/tabs.php#L227-L240

Ich überleg mir was ...

**Comment by christophboecker** [comment]
Gerne mal #54 testen, bei mir hat es funktoniert.

**Comment by MC-PMOE** [comment]
@christophboecker  Danke, läuft 👍

**Comment by alxndr-w** [comment]
Danke fürs melden und den prompten fix!
