### ISSUE TITLE
Scope der php-cs-fixer-Action überrascht

### ISSUE THREAD

**Issue by christophboecker** [alexplusde/yform_field#55]
Kleiner Hinweis zur php-cs-fixer-Action. Ich war etwas überrascht, dass die Action in #54 nicht nur die eine, im PR geänderte Datei bereinigt hat, sondern einmal über das gesamte Repo gelaufen ist. 

Ist das so Absicht im diesem Repo oder arbeitet die Action halt immer so?

Grund der Frage: es entsteht dann der Eindruck, dass im PR massenhaft Dateien bearbeitet wurden (30 Dateien) und damit die eigentliche Problemlösung (1 Datei) optisch untergeht. (Vermischung zweier unabhängige Themen in einem PR - Problemlösung und Style-Bereinigung).

**Comment by alxndr-w** [comment]
Ja, das war ein Schnellschuss von mir - besser wäre, wenn es nicht so wäre. Ich hatte noch nicht die Zeit, das besser zu machen und nochmal Thorben zu interviewen.

Wenn, dann würde ich gerne das gleich bei allen meinen Add-ons gut lösen.

**Comment by christophboecker** [comment]
na ja, wenn es einmal gelaufen ist, solte es für zukünftige PRs ja immer passgenau sein.

**Comment by alxndr-w** [comment]
Ich dachte gerade, es wäre gelöst, aber ich habe ja die Branch-Protection aktiviert, deswegen schlägt die Aktion wieder fehl.

https://github.com/alexplusde/yform_field/actions/runs/6962065124/job/18944996490

@eace können wir da mal gemeinsam drauf schauen?

**Comment by eaCe** [comment]
@alxndr-w sicher. Wenn der Fixer auf auto-commit und fix steht, klingt das aber nach richtigem Verhalten. 
Schreib mir gerne in Slack, Freitags oder am Wochenende ginge auch ein Call.

**Comment by alxndr-w** [comment]
Ein Jahr später... Puh, weiß ich ehrlich gesagt nicht, was ich mit dem issue machen soll. :/
