### ISSUE TITLE
URL ohne Pfadangabe führt zum 404-Fehler

### ISSUE THREAD

**Issue by Koala** [alexplusde/yform_field#61]
https://github.com/alexplusde/yform_field/blob/c40055f6193a4a26827c0c396434e0186297bace/assets/choice_status.js#L38

Bei einer Installation in einem Unterverzeichnis wird derzeit der Pfad dorthin ignoriert und es kommt zu einem 404-Fehler.

Mit ergänzter Pfadangabe funktioniert es (zumindest bei mir):

```
        url = window.location.origin;
        path = window.location.pathname;
        $.get(url + path + '?page=content&rex-api-call=choice_status', { 
```

**Comment by alxndr-w** [comment]
Gerne als PR, Unterordner verwende ich grundsätzlich nie.

**Comment by alxndr-w** [comment]
Ach, du hattest das bereits ohne PR commited! https://github.com/alexplusde/yform_field/commit/367da87a2e99bd332d0bed20f39a7120acb103bd

Das habe ich nicht gesehen. Danke. 

Nächstes Mal lieber als PR, dann landet das auch automatisch in der Changelog und für Mitwirkende ist das transparenter.

**Comment by Koala** [comment]
Tschuldigung 🙈

**Comment by alxndr-w** [comment]
Alles gut. Wollte es gerade selbst erledigen und hatte gesehen, es ist schon gemacht.

Zum Dank gab es in Neues deine Autoren-Tabelle :)
