### ISSUE TITLE
Felder aus YForm Field kenntlich machen

### ISSUE THREAD

**Issue by alxndr-w** [alexplusde/yform_field#67]
Per Outputfilter Klasse setzen, dann wie folgt stylen:

```
tr.yform-classes-famous th a:after {
    content: "yform_field";
    position: absolute;
    top: 0px;
    font-size: 8px;
    right: 2px;
}
tr.yform-classes-famous th a {
    position: relative;
}
```

![image](https://github.com/alexplusde/yform_field/assets/3855487/cae658e5-b9a5-466e-8687-a95728d910bb)

**Comment by alxndr-w** [comment]
Alternativ das hier anpassbarer als PR einreichen:
https://github.com/yakamara/yform/blob/98dcf3e521cca5bd9886496590ea0039fed4853b/plugins/manager/lib/yform/manager.php#L876-L883

**Comment by christophboecker** [comment]
Mal abgesehen davon, dass es eine schön platzsparende Darstelung ist: notfalls kann man auch eine eigene Kennung vor den Erklärtext setzen wie etwa "YF_Field: Datum- und Uhrzeiteingabe". So behelfe ich mir derzeit mit eigenen Feldern.

**Comment by alxndr-w** [comment]
Viel zu einfach 🫣. Ja, kann ich eigentlich so machen.

**Comment by alxndr-w** [comment]
![image](https://github.com/alexplusde/yform_field/assets/3855487/9e0ce172-29fe-420c-948b-86005bf8b5e7)
