### ISSUE TITLE
Bug: unvollständiges Statement in rex_yform_value_domain

### ISSUE THREAD

**Issue by christophboecker** [alexplusde/yform_field#69]
ich wollte grade die frische Version 2.3.4 ansehen, habe im Table-Manager eine Tabelle geöffnet um ein Feld hinzuzufügen.

Es whoopst mit dem Fehler:

**ParseError:** syntax error, unexpected token ")"
**File:** redaxo/src/addons/yform_field/lib/yform/value/domain.php
**Line:** 91

https://github.com/alexplusde/yform_field/blob/c35ec6d8072f8b7691d42d43109f943a7f3ab241/lib/yform/value/domain.php#L91

Es fehlt vermutlich ein `''` hinter dem `??`? Also

```
foreach (explode(',', $params['value'] ?? '') as $k) {
```

**Request-Uri:** .../redaxo/index.php?page=yform/manager/table_field&start=0&table_name=rex_myfirsttable&list=26dcd764
**Request-Method:** GET

**ParseError:** syntax error, unexpected token ")"
**File:** redaxo/src/addons/yform_field/lib/yform/value/domain.php
**Line:** 91

<details>
<summary>Stacktrace</summary>

| Function | File | Line |
| -------------------------------------------- | ------------------------------------------------------------- | -------- |
| rex_autoload::autoload | redaxo/src/addons/yform/lib/yform.php | 793 |
| rex_yform::getTypeArray | redaxo/src/addons/yform/plugins/manager/lib/yform/manager.php | 827 |
| rex_yform_manager->getFieldPage | redaxo/src/addons/yform/plugins/manager/pages/table_field.php | 20 |
| require | redaxo/src/core/lib/packages/package.php | 233 |
| rex_package->includeFile | redaxo/src/core/lib/be/controller.php | 503 |
| rex_be_controller::{closure} | redaxo/src/core/lib/util/timer.php | 56 |
| rex_timer::measure | redaxo/src/core/lib/be/controller.php | 485 |
| rex_be_controller::includePath | redaxo/src/core/lib/be/controller.php | 453 |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/yform/pages/index.php | 3 |
| require | redaxo/src/core/lib/packages/package.php | 233 |
| rex_package->includeFile | redaxo/src/core/lib/be/controller.php | 503 |
| rex_be_controller::{closure} | redaxo/src/core/lib/util/timer.php | 56 |
| rex_timer::measure | redaxo/src/core/lib/be/controller.php | 485 |
| rex_be_controller::includePath | redaxo/src/core/lib/be/controller.php | 436 |
| rex_be_controller::includeCurrentPage | redaxo/src/core/backend.php | 241 |
| require | redaxo/src/core/boot.php | 155 |
| require | /......./redaxo/index.php | 9 |

</details>
<details>
<summary>System report (REDAXO 5.15.1, PHP 8.2.15, MySQL 8.0.17)</summary>

| REDAXO | |
| ------------: | :--------- |
| Version | 5.15.1 |

| PHP | |
| ------------: | :----------------------------- |
| Version | 8.2.15 |
| OPcache | yes |

| Database | |
| ------------: | :----------- |
| Version | MySQL 8.0.17 |
| Character set | utf8 |

| Server | |
| ------------: | :------------- |
| OS | Darwin |
| SAPI | apache2handler |
| Webserver | Apache/2.4.58 |

| Request | |
| ------------: | :------------ |
| Browser | Firefox/122.0 |
| Protocol | HTTP/1.1 |
| HTTPS | no |

| Packages | |
| ------------------: | :--------- |
| adminer | 1.9.3 |
| backup | 2.9.0 |
| be_style | 3.2.0 |
| be_style/customizer | 3.2.0 |
| be_style/redaxo | 3.2.0 |
| cheatsheet | 0.0.1 |
| cronjob | 2.10.0 |
| developer | 3.9.2 |
| focuspoint | 4.2.0 |
| geolocation | 2.1.2 |
| install | 2.11.1 |
| media_manager | 2.14.0 |
| mediapool | 2.13.0 |
| metainfo | 2.10.0 |
| phpmailer | 2.12.0 |
| project | 0.0.0 |
| rexstan | 1.0.160 |
| structure | 2.15.0 |
| structure/content | 2.15.0 |
| users | 2.10.0 |
| yform | 4.1.1 |
| yform/email | 4.1.1 |
| yform/manager | 4.1.1 |
| yform/tools | 4.1.1 |
| yform_adminer | 1.2.0 |
| yform_field | 2.3.4 |

</details>

**Comment by alxndr-w** [comment]
Hoppla. Danke!
