### ISSUE TITLE
Class "rex_var_custom_url" not found

### ISSUE THREAD

**Issue by isospin** [alexplusde/yform_field#84]
nach update von YFORM_FIELD 2.6 auf 2.7 liefert die datensatz detailansicht im tablemanager folgende fehlermeldung:
`Transaktion wurde wegen folgendem Fehler nicht ausgeführt: Class "rex_var_custom_url" not found`

REDAXO 	5.17.1
PHP 	8.3.8 
YFORM	4.2.1

**Comment by alxndr-w** [comment]
@skerbis das war das Feld, was ich aus MForm übernommen habe. Ich habe leider die nächsten 14 Tage keine Möglichkeit mehr, mich darum zu kümmern. Könntest du es dir anschauen?

@isospin ich habe das Feld selbst leider weder entwickelt, noch im Einsatz, deswegen - wenn du es gelöst bekommst, gerne einen PR oder dich mit @skerbis absprechen.

**Comment by skerbis** [comment]
Na ja die Class ist nicht im Addon würd ich sagen. Hast du das abhängig von mform gemacht? @alxndr-w ?

**Comment by alxndr-w** [comment]
Nein, eigentlich unbenannt damit es sich nicht in die Quere kommt. Du könntest im passenden PR Mal prüfen, ob ich was übersehen habe.

**Comment by akuehnis** [comment]
Quickfix (ohne gewähr):

addons/yform_field/lib/yform/value/custom_link.php

addons/yform_field/ytemplates/bootstrap/value.custom_link.tpl.php

Ersetze rex_var_custom_url durch rex_var_custom_link.
