### ISSUE TITLE
Transaktion wurde wegen folgendem Fehler nicht ausgeführt: Class "rex_var_custom_url" not found

### ISSUE THREAD

**Issue by bitshiftersgmbh** [alexplusde/yform_field#86]
Aktueller Release 2.7.1
Datei: redaxo/src/addons/yform_field/lib/yform/value/custom_link.php
Fehlermeldung: _siehe Issue Title_
tritt auf: wenn man einen Datensatz einer Table anlegen/editieren will, wo ein `custom_link`-Feld benutzt wird

![image](https://github.com/user-attachments/assets/419772d5-f699-482c-8f31-0a58ba3734c9)

**Comment by bitshiftersgmbh** [comment]
Siehe https://github.com/alexplusde/yform_field/commit/08114122b70062f8b47c3e3de0e9d150b0d5a716#diff-06b970847986128d64ae668b61daf6e4228c596581ff251051fb343fb7c989ccR53

**lib/yform/value/custom_link.php**

Müsste es nicht `return rex_var_custom_link::getCustomLinkText($params['value']);` heißen? Die Methode mit "url" gibt es in MForm 8.0.4 auf jeden Fall nicht.

**Comment by alxndr-w** [comment]
Fix gerne als PR beisteuern - ich verwende das Feld nicht, ich möchte nur ein wenig die unterschiedlichen Lösungen die so rumgeistern für YForm vereinen.

**Comment by alxndr-w** [comment]
fixed in https://github.com/alexplusde/yform_field/tree/hotfix-issue-84
